### PR TITLE
fix template page permissions issue

### LINKED ISSUE #479: Markdown file for 404 page created with read-only permissions
I can't figure out where I need to go to debug  an issue I'm seeing. When creating the 404 page, the markdown file (`/tmp/RtmpmaiZ5B/file73cdc48b90540.md` in the example below) is being created with read-only permissions. Something then wants to open this file with append permission and fails.
```
── Creating 404 page ───────────────────────────────────────────────────────────────────────────────────────────────────
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning messages:
1: replacing previous import ‘lifecycle::last_warnings’ by ‘rlang::last_warnings’ when loading ‘tibble’ 
2: replacing previous import ‘ellipsis::check_dots_unnamed’ by ‘rlang::check_dots_unnamed’ when loading ‘tibble’ 
3: replacing previous import ‘ellipsis::check_dots_used’ by ‘rlang::check_dots_used’ when loading ‘tibble’ 
4: replacing previous import ‘ellipsis::check_dots_empty’ by ‘rlang::check_dots_empty’ when loading ‘tibble’ 
5: In bind_rows_(x, .id) :
  Vectorizing 'fs_path' elements may not preserve their attributes
6: In bind_rows_(x, .id) :
  Vectorizing 'fs_path' elements may not preserve their attributes
7: In file(file, ifelse(append, "a", "w")) :
  cannot open file '/tmp/RtmpmaiZ5B/file73cdc48b90540.md': Permission denied
```
I do not control most of the R installation, and I've only updated what I needed to update to get things working. Could it a versions issue with one of the packages I am using?
```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Rocky Linux 8.8 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/intel/skylake_avx512/software/OpenBLAS/0.3.9-GCC-9.3.0/lib/libopenblas_skylakexp-r0.3.9.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      pillar_1.4.3      compiler_4.0.0    tools_4.0.0       sys_3.3           downlit_0.4.2    
 [7] digest_0.6.25     memoise_1.1.0     evaluate_0.14     lifecycle_0.2.0   tibble_3.0.1      pkgconfig_2.0.3  
[13] rlang_1.1.0       varnish_0.2.17    cli_3.6.0         rstudioapi_0.11   commonmark_1.7    yaml_2.2.1       
[19] pkgdown_2.0.7     xfun_0.13         fastmap_1.1.0     withr_2.5.0       dplyr_0.8.5       sandpaper_0.12.3 
[25] knitr_1.28        tinkr_0.2.0       xml2_1.3.2        desc_1.2.0        fs_1.5.2          vctrs_0.2.4      
[31] askpass_1.1       tidyselect_1.0.0  pegboard_0.5.2    rprojroot_1.3-2   gert_1.9.2        glue_1.4.0       
[37] R6_2.4.1          processx_3.4.2    rmarkdown_2.20    callr_3.4.3       purrr_0.3.4       magrittr_1.5     
[43] whisker_0.4       backports_1.1.6   ps_1.3.2          credentials_1.3.2 ellipsis_0.3.0    htmltools_0.5.2  
[49] assertthat_0.2.1  xslt_1.4.4        openssl_2.0.6     crayon_1.3.4
```

The weird thing is I am reproducing an environment that I already used successfully...so I am lost.

### PR DESCRIPTION
**Pull request by zkamvar**
This ensures that templated files have the right permissions when appending common links to them so that 404 pages and other generated content can be built.

This will fix #479

This PR can be tested by installing it with the `{pak}` OR `{remotes}` package:

```r
# via {pak}
# install.packages("pak")
pak::pkg_install("carpentries/sandpaper#482")

# via {remotes}
# install.packages("remotes")
remotes::install_github("carpentries/sandpaper#482")
```

### CODE REVIEW

File: R/render_html.R [hunk 1]
```diff
@@ -49,6 +49,9 @@ render_html <- function(path_in, ..., quiet = FALSE) {
     # if we have links, we concatenate our input files
     tmpin <- tempfile(fileext = ".md")
     fs::file_copy(path_in, tmpin)
+    # if the file is not readable by the user, then we need to make it readable
```
Comment (ocaisa) [inline R/render_html.R:52]:
```suggestion
    # if the file is not writable by the user, then we need to make it writable
```

**Review by ocaisa — COMMENTED** [review]
Typo

File: R/render_html.R (hunk 1 above)
Comment (zkamvar) [reply R/render_html.R]: good catch! Thank you
